"Changes: Python":
  - changed-files:
      - '**/*.py'

"Changes: Documentation":
  - changed-files:
      - '**/*.md'
      - '**/*.rst'
      - '**/*.txt'

"Changes: Tests":
  - changed-files:
      - '/tests/**/*.py'
      - '**/test_*.py'

"Changes: Requirements":
  - changed-files:
      - '**/requirements.txt'
      - '**/Pipfile'
      - '**/Pipfile.lock'

"Changes: Config":
  - changed-files:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.ini'
      - '**/*.json'

"Changes: Docs Generator":
  - changed-files:
      - '**/*.rst'
      - '**/*.md' # TODO: возможно ещё добавить 

"Changes: No Python":
  - changed-files:
      - '**/*' 
  - exclude:
      - '**/*.py'  # исключаем .py файлы

"Changes: GitHub":
  - changed-files:
      - '/.github/'
