name: Run Bot

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
      - run: python main.py
        env:
          DISCORD_KEY: ${{ secrets.DISCORD_KEY }} }