 name: Restart Discord Bot

 on:
  schedule:
    - cron: '*/10 * * * *'

 jobs:
  restart:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: CheckBotStatus and Restart
        uses: actions/github-script@v5
        with:
          script: |
            const workflowRuns = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy'
            });
            const lastRun = workflowRuns.data.workflow_runs[0];
            console.log(lastRun.status);
            if (lastRun.status === 'completed') {
              console.log('Bot is already running');
            } else {
              await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'deploy', 
              });
              console.log('Restarting Discord Bot...');
            }
 
