# name: Deploy Discord Bot

# on:
#   schedule:
#     # Запускать каждые 6 часов
#     - cron: '0 */6 * * *'  # Каждый 6-й час, в 0 минут

#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.11'

#       - name: Install MariaDB Connector/C
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y libmariadb-dev

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Load Environment Variables
#         run: |
#           echo "DISCORD_KEY=${{ secrets.DISCORD_KEY }}" >> $GITHUB_ENV
#           echo "GITHUB=${{ secrets.GITHUB }}" >> $GITHUB_ENV
#           echo "USER=${{ secrets.USER }}" >> $GITHUB_ENV
#           echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
#           echo "HOST=${{ secrets.HOST }}" >> $GITHUB_ENV
#           echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
#           echo "DATABASE=${{ secrets.DATABASE }}" >> $GITHUB_ENV

#       - name: Check if bot is already running
#         run: |
#           if pgrep -f "python main.py" > /dev/null; then
#             echo "Bot is already running, skipping start."
#             exit 0
#           fi

#       - name: Run bot
#         env:
#           DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
#         run: |
#           echo "Starting the bot..."
#           python main.py

name: Deploy Discord Bot

on:
  schedule:
    # Запускать каждые 10 минут
    - cron: '*/10 * * * *'  # Каждые 10 минут
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install MariaDB Connector/C
        run: |
          sudo apt-get update
          sudo apt-get install -y libmariadb-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load Environment Variables
        run: |
          echo "DISCORD_KEY=${{ secrets.DISCORD_KEY }}" >> $GITHUB_ENV
          echo "GITHUB=${{ secrets.GITHUB }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.USER }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "HOST=${{ secrets.HOST }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          echo "DATABASE=${{ secrets.DATABASE }}" >> $GITHUB_ENV

      - name: Check if another deployment is running
        run: |
          CURRENT_RUN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=${{ github.ref }}" | \
            jq -r '.workflow_runs[0].id')

          PREVIOUS_RUN_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${CURRENT_RUN_ID}" | jq -r '.status')

          if [[ "$PREVIOUS_RUN_STATUS" == "in_progress" ]]; then
            echo "Another bot deployment is in progress, skipping."
            exit 0
          fi

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          echo "Starting the bot..."
          nohup python main.py


