name: Deploy Discord Bot

on:
  schedule:
    # Запускать каждые 5 часов
    - cron: '0 */5 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load Environment Variables
        run: |
          echo "DISCORD_KEY=${{ secrets.DISCORD_KEY }}" >> $GITHUB_ENV
          echo "GITHUB=${{ secrets.GITHUB }}" >> $GITHUB_ENV

      - name: Kill previous bot instance (if running)
        run: |
          pkill -f main.py || true

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          python main.py &