name: Deploy Bot to Server

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    if: ${{ vars.DEPLOY_ENABLED != 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server and restart bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Dev-bot
            git reset --hard
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pm2 restart Dev-Bot || pm2 start /root/Dev-bot/venv/bin/python --name Dev-Bot -- /root/Dev-bot/main.py
