name: Linter Python Code

on:
  pull_request:
    branches:
      - main
      - develop
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-cache-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pylint

    - name: Run flake8
      run: |
        flake8 . --max-line-length=120

    - name: Run Pylint
      run: |
        pylint **/*.py --disable=R,C --max-line-length=120

    - name: Run Pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: test-report.xml

    - name: Upload Pylint report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: pylint-report
        path: pylint-report.txt

    - name: Upload Flake8 report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: flake8-report.txt
