name: Linter Python Code

on:
  push:
    branches:
      - main
      - develop
      - dev
  pull_request:
    branches:
      - main
      - develop
      - dev

jobs:
  py-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MariaDB Connector/C
      run: |
        sudo apt-get update
        sudo apt-get install -y libmariadb-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-cache-

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    #     pip install asyncio logging aiohttp pyyaml

    - name: Run Pylint
      run: |
        pip install pylint
        pylint **/*.py

    # - name: Upload Pylint report
    #   if: failure()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: pylint-report
    #     path: pylint-report.txt

    - name: Summary
      run: |
        echo "Python Linter completed. Check the results above."