name: Run Bot

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        env:
          DISCORD_KEY: ${{ secrets.DISCORD_KEY }}
          USER_KEY_GITHUB: ${{ secrets.USER_KEY_GITHUB }}
          POST_PASSWORD_MRP: ${{ secrets.POST_PASSWORD_MRP }}
          POST_PASSWORD_DEV: ${{ secrets.POST_PASSWORD_DEV }}
          POST_AUTHORIZATION_MRP: ${{ secrets.POST_AUTHORIZATION_MRP }}
          POST_AUTHORIZATION_DEV: ${{ secrets.POST_AUTHORIZATION_DEV }}
          POST_USER_AGENT: ${{ secrets.POST_USER_AGENT }}
          ADMIN_API: ${{ secrets.ADMIN_API }}
          ADMIN_GUID: ${{ secrets.ADMIN_GUID }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          DATABASE_MRP: ${{ secrets.DATABASE_MRP }}
          DATABASE_DEV: ${{ secrets.DATABASE_DEV }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_PASS: ${{ secrets.DATABASE_PASS }}

        run: python main.py